name: xcat_ssm
channels:
- conda-forge
- nodefaults
dependencies:
- pytorch-gpu *
- numpy >=2.3.2,<3
- nibabel >=5.3.2,<6
- scipy >=1.16.1,<2
- matplotlib >=3.10.5,<4
- pyvista >=0.46.3,<0.47
- tqdm >=4.67.1,<5
- scikit-learn >=1.7.2,<2
- einops >=0.8.1,<0.9
- typer >=0.19.2,<0.20
- pip
- pip:
  - --index-url https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple
  - torchcpd @ git+https://github.com/mikami520/CPD-Pytorch.git@0fd2ec50109582f5992fc9b5eb2ef512d144a481
  - pyacvd>=0.3.2, <0.4